name: AWSRekognitionAnalysis
description: This function analyzes an image file using AWS Rekognition.
runtime: python3_10
interface:
  inputs:
    properties:
      image_file:
        type: file
        description: The image file to analyze.
      AWS_ACCESS_KEY_ID:
        type: env
        description: AWS Access Key ID.
      AWS_SECRET_ACCESS_KEY:
        type: env
        description: AWS Secret Access Key.
      AWS_REGION:
        type: env
        description: AWS Region.
      types:
        type: array
        items:
          type: string
          description: The type of analysis to perform. Options are 'labels' or 'text' or 'faces' or 'celebrities'.
          default: labels
    required:
      - image_file
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
  outputs:
    properties:
      labels:
        type: array
        description: The detected labels from the image.
      text:
        type: array
        description: The detected text from the image.
      faces:
        type: array
      celebrities:
        type: array
