description: Clone a Git repository (including private ones) to a temporary directory, with options for sub-paths and refs, using nodegit.
interface:
  inputs:
    repoUrl:
      type: string
      description: The URL of the Git repository to clone.
    privateToken:
      type: string
      description: A token for accessing private repositories. Optional.
      optional: true
    path:
      type: string
      description: A sub-path within the repository to return.
    ref:
      type: string
      description: A reference within the repository to checkout (branch, tag, or commit). Optional.
      optional: true
  outputs:
    status:
      type: string
      description: Success or failure message.
    repoCode:
      type: file
      description: The path to the cloned sub-path in the local file system.
runtime: nodejs20
