apiRevision: edurata.io/v1
name: clone-git
description: Clones a git repo
runtime: docker
registry:
  url: edurata/clone-git
  tag: latest
interface:
  inputs:
    properties:
      repoUrl:
        type: string
        description: The url of the git repo.
      path:
        type: string
        description: The path to inside the repo to return.
        default: ""
      ref:
        type: string
        description: The git ref to checkout.
        default: "main"
      privateUser:
        type: string
        description: The private user to use for authentication.
      privateToken:
        type: string
        description: The private token to use for authentication.
    required:
      - repoUrl
  outputs:
    properties:
      repoCode:
        type: file
        description: The downloaded git repo
