apiRevision: edurata.io/function/v1
name: chatgpt-command
description: |
  Make one command to chat with gpt-3.
runtime: nodejs20
interface:
  inputs:
    properties:
      systemMessage:
        type: string
        description: The message to signal the behaviour of the assistant.
        default: You are a helpful assistant.
      message:
        type: string
        description: The message to send to gpt-3.
      model:
        type: string
        description: The model to use
        enum: [gpt-3.5-turbo, gpt-4o]
        default: gpt-3.5-turbo
      API_KEY:
        type: env
        description: The deepl api key.
    required: [message, API_KEY]
  outputs:
    properties:
      response:
        type: string
        description: The response by gpt-3
