apiRevision: edurata.io/v1
name: read-from-s3
description: |
  Takes a file from s3 and converts it to json so it can be used as config
runtime: python3_8
interface:
  inputs:
    properties:
      AWS_ACCESS_KEY_ID:
        type: env
        description: The aws access key id
      AWS_SECRET_ACCESS_KEY:
        type: env
        description: The aws secret access key
      AWS_REGION:
        type: env
        description: The aws region
        default: eu-central-1
      bucket_name:
        type: string
        description: The twitter api secret
      s3_file_key:
        type: string
        description: The twitter api key
      local_file_path:
        type: string
        description: If undefined, will only be available in output
      is_json:
        type: boolean
        description: If true, will try to parse the file as json
        default: false
    required:
      - bucket_name
      - s3_file_key
  outputs:
    properties:
      file:
        type: file
        description: The file downloaded from s3
      content:
        type: object
        description: The content of the file downloaded from s3
