name: create_gdrive_folder_path
runtime: nodejs20
interface:
  inputs:
    properties:
      OAUTH_TOKEN:
        type: env
        description: "OAuth token for Google Drive API."
      folder_path:
        type: string
        description: "The folder path to create in Google Drive, e.g., 'hello/foo/bar'."
    required: ["folder_path"]
  outputs:
    properties:
      message:
        type: string
        description: "Status message of the folder creation process."
