apiRevision: edurata.io/function/v1
name: tweet
description: |
  Wrapper for Twitter API to make a tweet.
runtime: python3_10
interface:
  inputs:
    properties:
      BEARER_TOKEN:
        type: env
        description: The Twitter bearer token
      message:
        type: string
        description: The message to tweet
      mediaPath:
        type: file
        description: The path to the media to tweet (optional)
    required:
      - BEARER_TOKEN
      - message
  outputs:
    properties:
      success:
        type: boolean
        description: The success of the operation
