apiRevision: edurata.io/v1
name: tweet
description: |
  wrapper for twitter api to make a tweet
runtime: python3_10
interface:
  inputs:
    properties:
      API_KEY:
        type: env
        description: The twitter api key
      API_SECRET:
        type: env
        description: The twitter api secret
      ACCESS_TOKEN:
        type: env
        description: The twitter access token
      ACCESS_TOKEN_SECRET:
        type: env
        description: The twitter access token secret
      BEARER_TOKEN:
        type: env
        description: The twitter bearer token
      messages:
        type: array
        description: The messages to tweet
        items:
          type: string
      mediaPaths:
        type: array
        description: The paths to the media to tweet
        items:
          type: string
    required:
      - API_KEY
      - API_SECRET
      - ACCESS_TOKEN
      - ACCESS_TOKEN_SECRET
      - BEARER_TOKEN
      - messages
  outputs:
    properties:
      success:
        type: boolean
        description: The success of the operation
