apiRevision: edurata.io/v1
name: translate-deepl
description: |
  Generic function to call apis using axios.
runtime: nodejs18
entrypoint: dist/tsc/index.js
include:
  - dist/tsc/**
interface:
  inputs:
    properties:
      sourceTexts:
        type: array
        description: The path to the source texts
        items:
          type: string
      DEEPL_API_KEY:
        type: env
        description: The deepl api key
      targetLanguage:
        type: string
        description: The target language
    required: [sourceTextsPath, apiKey, sourceLanguage, targetLanguage]
  outputs:
    properties:
      translations:
        type: array
        description: The path to the translated texts
        items:
          type: string
