apiRevision: edurata.io/v1
name: download-s3
description: |
  wrapper to download file from s3
runtime: python3_8
interface:
  inputs:
    properties:
      bucket_name:
        type: string
        description: The twitter api secret
      s3_file_key:
        type: env
        description: The twitter api key
      local_file_path:
        type: env
        description: If undefined, will only be available in output
    required:
      - bucket_name
      - s3_file_key
  outputs:
    properties:
      file:
        type: file
        description: The file downloaded from s3
