apiRevision: edurata.io/v1
name: create-linkedin-post
description: |
  Creates a post on linkedin
  - https://learn.microsoft.com/en-us/linkedin/marketing/community-management/shares/posts-api?view=li-lms-2024-02&tabs=http#create-a-post
  - https://learn.microsoft.com/en-us/linkedin/marketing/community-management/shares/images-api?view=li-lms-2024-02&tabs=http
runtime: python3_10
interface:
  inputs:
    properties:
      LINKEDIN_API_SECRET:
        type: env
        description: The linkedin api key
      text:
        type: string
        description: The text to post
      mediaType:
        type: string
        description: The type of media to post
        enum:
          - image
          - video
      sponsored:
        type: boolean
        description: Whether the post is sponsored
        default: false
      mediaPaths:
        type: array
        description: The paths to the media to post
        items:
          type: file
          description: The path to the media to post
    required: [LINKEDIN_API_SECRET, text]
  outputs:
    status:
      type: string
      description: The status of the post
    response:
      type: string
      description: The response
