apiRevision: edurata.io/v1
name: axios
description: |
  Generic function to call apis using axios
runtime: nodejs18
entrypoint: dist/tsc/index.js
include: dist/tsc/**
interface:
  inputs:
    properties:
      url:
        type: string
        description: The url to fetch
      method:
        type: string
        description: The http method
      headers:
        type: object
        description: The http headers
      body:
        type: object
        description: The http body
    required: [url]
  outputs:
    properties:
      response:
        type: object
        properties:
          status:
            type: number
            description: The http status code
          data:
            type: object
            description: The http response body
          headers:
            type: object
            description: The http response headers
          config:
            type: object
            description: The http request config
          request:
            type: object
            description: The http request
          statusText:
            type: string
            description: The http status text
          response:
            type: object
            description: The http response
          message:
            type: string
            description: The http response message
          isAxiosError:
            type: boolean
            description: Is this an axios error
          toJSON:
            type: function
            description: Convert to json
          name:
            type: string
            description: The http response name
          stack:
            type: string
            description: The http response stack
          code:
            type: string
            description: The http response code
