name: text_extractor
description: A function to scrape a website at a given URL and return the text content using Crawlbase.
runtime: python3_10
interface:
  inputs:
    properties:
      CRAWL_PASSWORD:
        type: env
        description: Crawlbase API password.
      url:
        type: string
        description: The URL of the website to scrape.
    required:
      - url
      - CRAWL_PASSWORD
  outputs:
    properties:
      text:
        type: string
        description: The text content of the scraped website.
    required:
      - text
