apiRevision: edurata.io/v1
name: axios
description: |
  Generic function to call apis using axios.
runtime: nodejs20
entrypoint: dist/tsc/index.js
include:
  - dist/tsc/**
interface:
  inputs:
    properties:
      url:
        type: string
        description: The url to fetch
      method:
        type: string
        description: The http method
      headers:
        type: object
        description: The http headers
      body:
        type: object
        description: The http body
    required: [url]
  outputs:
    properties:
      response:
        type: object
        properties:
          data:
            type: object
            description: The http response body
          status:
            type: number
            description: The http status code
          statusText:
            type: string
            description: The http status text
          headers:
            type: object
            description: The http response headers
      error:
        type: object
        properties:
          message:
            type: string
            description: The error message
          code:
            type: string
            description: The error code
          config:
            type: object
            description: The http request config
          request:
            type: object
            description: The http request
          response:
            type: object
            description: The http response
          isAxiosError:
            type: boolean
            description: Whether the error is an axios error
    required: [response]
