apiRevision: edurata.io/function/v1
runtime: python3_10
description: Installs python packages..
interface:
  inputs:
    properties:
      code:
        type: file
        description: The code with requirements.txt
    required: [code]
  outputs:
    properties:
      code:
        type: file
        description: With the modules installed
