name: mysql_query_function
handler: index.handler
runtime: python3_10
interface:
  inputs:
    properties:
      query:
        type: string
        description: The query to execute
      MYSQL_HOST:
        type: env
        description: The host of the MySQL server
      MYSQL_USER:
        type: env
        description: The user to connect to the MySQL server
      MYSQL_PASSWORD:
        type: env
        description: The password to connect to the MySQL server
      MYSQL_DATABASE:
        type: env
        description: The database to connect to
  outputs:
    properties:
      result:
        type: string
        description: The stringified result of the query
      error:
        type: string
        description: The error message if the query failed
