apiVersion: "0.0.1"
title: Api function
name: crud
description: A versatile api function that can be templated to generate functions based on an openApi schema
action: CRUD
multiple: true
schema: 
  url: https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/amazonaws.com/s3/2006-03-01/openapi.yaml
interface:
