apiRevision: edurata.io/v1
name: data-to-s3
description: |
  wrapper to upload data to s3
runtime: nodejs20
interface:
  inputs:
    properties:
      AWS_ACCESS_KEY_ID:
        type: env
        description: The aws access key id
      AWS_SECRET_ACCESS_KEY:
        type: env
        description: The aws secret access key
      AWS_REGION:
        type: env
        description: The aws region
        default: eu-central-1
      bucket_name:
        type: string
        description: The bucket name
      files:
        type: array
        description: The files to upload
        properties:
          content:
            type: string
            description: Pass this in if you want to upload data directly
          path:
            type: file
            description: Pass this if you want to upload a file
          key:
            type: string
            description: The s3 file key
    required:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - bucket_name
  outputs:
    properties:
      success:
        type: boolean
        description: The success of the operation
