name: GoogleSheetsAPIClient
description: A function to make calls to Google Sheets API using an OAuth token.
interface:
  inputs:
    properties:
      spreadsheet_id:
        type: string
        description: The ID of the Google Sheets spreadsheet.
      range:
        type: string
        description: The range of cells to read or write.
      oauth_token:
        type: string
        description: The OAuth token for authentication.
      data:
        type: object
        description: The data to write to the spreadsheet (required for write operations). If not present will assume read.
    required:
      - spreadsheet_id
      - range
      - oauth_token
  outputs:
    properties:
      response:
        type: object
        description: The response from the Google Sheets API.
    required:
      - response
