apiRevision: edurata.io/v1
name: invoice-forwarder
description: |
  Email forwarder based on the ahochsteger/gmail-processor
runtime: nodejs20
entrypoint: dist/tsc/index.js
include:
  - dist/tsc/**
interface:
  inputs:
    type: object
    properties:
      files:
        type: array
        items:
          type: file
  outputs:
