name: pdf_text_filler
runtime: python3_10
interface:
  inputs:
    properties:
      pdf_path:
        type: file
      fields_data:
        type: array
        items:
          type: object
          properties:
            field_name:
              type: string
            field_value:
              type: string
          required:
            - field_name
            - field_value
  outputs:
    properties:
      filled_pdf_path:
        type: file
    required:
      - filled_pdf_path
  description: Fills in text fields inside a PDF based on the given field names and values, and saves the filled PDF.
