apiRevision: edurata.io/v1
name: fetch-weather
runtime: nodejs18
interface:
  inputs:
    properties:
      lat:
        type: number
        description: |
          Latitude
      long:
        type: number
        description: |
          Longitude
      date:
        type: string
        description: |
          Date in YYYY-MM-DD format.
    required:
      - lat
      - long
  outputs:
    properties:
      coord:
        lon:
          type: number
          description: Longitude
        lat:
          type: number
          description: Latitude
      weather:
        type: array
        items:
          type: object
          properties:
            id:
              type: number
              description: Weather condition id
            main:
              type: string
              description: Group of weather parameters (Rain, Snow, Extreme etc.)
            description:
              type: string
              description: Weather condition within the group
            icon:
              type: string
              description: Weather icon id
      base:
        type: string
        description: Internal parameter
      main:
        type: object
        properties:
          temp:
            type: number
            description: "Temperature. Unit Default: Kelvin, Metric: Celsius, Imperial: Fahrenheit."
          feels_like:
            type: number
            description: Temperature. This temperature parameter accounts for the human perception of weather.
          temp_min:
            type: number
            description: Minimum temperature at the moment of calculation. This is minimal currently observed temperature (within large megalopolises and urban areas).
          temp_max:
            type: number
            description: Maximum temperature at the moment of calculation. This is maximal currently observed temperature (within large megalopolises and urban areas).
          pressure:
            type: number
            description: Atmospheric pressure on the sea level, hPa
          humidity:
            type: number
            description: Humidity, %
          sea_level:
            type: number
            description: Atmospheric pressure on the sea level, hPa
          grnd_level:
            type: number
            description: Atmospheric pressure on the ground level, hPa

      visibility:
        type: number
        description: Visibility, meter
      wind:
        type: object
        properties:
          speed:
            type: number
            description: "Wind speed. Unit Default: meter/sec, Metric: meter/sec, Imperial: miles/hour."
          deg:
            type: number
            description: Wind direction, degrees (meteorological)
          gust:
            type: number
            description: "Wind gust. Unit Default: meter/sec, Metric: meter/sec, Imperial: miles/hour"
      rain:
        type: object
        properties:
          1h:
            type: number
            description: Rain volume for the last 1 hour, mm
          3h:
            type: number
            description: Rain volume for the last 3 hours, mm

      clouds:
        type: object
        properties:
          all:
            type: number
            description: Cloudiness, %
      dt:
        type: number
        description: Time of data calculation, unix, UTC
      sys:
        type: object
        properties:
          type:
            type: number
            description: Internal parameter
          id:
            type: number
            description: Internal parameter
          country:
            type: string
            description: Country code (GB, JP etc.)
          sunrise:
            type: number
            description: Sunrise time, unix, UTC
          sunset:
            type: number
            description: Sunset time, unix, UTC
      timezone:
        type: number
        description: Shift in seconds from UTC
      id:
        type: number
        description: City ID
      name:
        type: string
        description: City name
      cod:
        type: number
        description: Internal parameter
