name: html_to_pdf_converter
runtime: nodejs20
interface:
  inputs:
    properties:
      html_file:
        type: file
        description: "Path to the HTML file to be converted to PDF."
    required: ["html_file"]
  outputs:
    properties:
      pdf_file:
        type: file
        description: "Path to the generated PDF file."
